### ISSUE TITLE
Fails parsing hex files with \r\n line ending

### ISSUE THREAD

**Issue by somemetricprefix** [martinmroz/ihex#1]
Using this package with hex files that were created on a windows system (\r\n line ending) results in RecordNotEvenLength errors.

**Comment by martinmroz** [comment]
Ah, good catch, I'll look into this tonight and try and have a fix out then.

**Comment by martinmroz** [comment]
Publish 1.0.1 with a fix, if it doesn't work for you for some reason, please file a new ticket!

**Comment by somemetricprefix** [comment]
Works like a charm! Thank you for the very fast fix.
