### ISSUE TITLE
Error in writer.rs

### ISSUE THREAD

**Issue by skrapi** [martinmroz/ihex#11]
I am trying to use ihex for some hex analysis and I wanted to get a Display implementation for Record, while messing around with it, I got this error:
``` sh
error[E0277]: a value of type `std::result::Result<std::vec::Vec<std::string::String>, writer::WriterError>` cannot be built from an iterator over elements of type `std::string::String`
   --><MYDIR>/ihex/src/writer.rs:192:10
    |
192 |         .collect::<Result<Vec<String>, WriterError>>()
    |          ^^^^^^^ value of type `std::result::Result<std::vec::Vec<std::string::String>, writer::WriterError>` cannot be built from `std::iter::Iterator<Item=std::string::String>`
    |
    = help: the trait `std::iter::FromIterator<std::string::String>` is not implemented for `std::result::Result<std::vec::Vec<std::string::String>, writer::WriterError>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `ihex`.
```

I don't have enough Rust experience to fix this yet, so posting hoping one of the contributors have an idea of a fix.

**Comment by skrapi** [comment]
The problem is that ```to_string()``` implementation for Record was conflicting with a String::to_string

**Comment by skrapi** [comment]
#12 Fixes this

**Comment by martinmroz** [comment]
Good catch, I wrote this back when I was starting out in Rust -- but I have a personal policy of open-sourcing any projects others might find useful -- so I likely had no idea what I was doing haha. Thanks for contributing the fix!

**Comment by martinmroz** [comment]
If you'd like to take a look @skrapi, I've folded a bunch of changes into 2.0
https://github.com/martinmroz/ihex/pull/13
