### ISSUE TITLE
License

### ISSUE THREAD

**Issue by drahnr** [martinmroz/ihex#4]
Would you consider making it dual licensed to `MIT OR Apache-2.0`? Reasons have been discussed fully i.e. https://github.com/lo48576/fbx_direct/issues/1

Thanks for creating this awesome crate!

**Comment by martinmroz** [comment]
Happy to! Glad you've found it useful.

**Comment by martinmroz** [comment]
I'll take care of the licensing updates today, I've been going through my crates to get off travis-cargo and onto cargo-travis so I'll do that also.

**Comment by martinmroz** [comment]
https://github.com/martinmroz/ihex/pull/5 If you're cool with this, and ok relicensing your changes, I'll merge it now.
